export const FETCH_TEMPLATES_REQUESTED = "FETCH_TEMPLATES_REQUESTED";
export const FETCH_TEMPLATES_SUCCESS = "FETCH_TEMPLATES_SUCCESS";
export const FETCH_TEMPLATES_FAILURE = "FETCH_TEMPLATES_FAILURE";

export const DELETE_TEMPLATE_REQUESTED = "DELETE_TEMPLATE_REQUESTED";
export const DELETE_TEMPLATE_SUCCESS = "DELETE_TEMPLATE_SUCCESS";
export const DELETE_TEMPLATE_FAILURE = "DELETE_TEMPLATE_FAILURE";
